### ISSUE TITLE
Hi there, how to use this mod please?

### ISSUE THREAD

**Issue by CrayzCrinkle** [xyonico/CustomAvatarsPlugin#24]
Per title, unzipped to beat saber folder. Nothing is showing in game, it's not showing under the mods menu.

**Comment by Assistant** [comment]
Can't reproduce.

**Comment by CrayzCrinkle** [comment]
Sorry could you just explain? I am asking how to use the mod. I have downloaded and put it where i think is the right place but nothing is happening, therefore I came looking for instructions?
