### ISSUE TITLE
When starting new song, the avatar spawn location doesn't take room adjustments into account

### ISSUE THREAD

**Issue by Shadnix-was-taken** [xyonico/CustomAvatarsPlugin#5]
I had some weird issues with custom avatars showing up in front of me and looking at me when starting a song in BeatSaber. This issue is new and appeared after updating the CustomAvatar plugin to v3.1.1-beta (and updating BeatSaber to v0.11.2). Previous versions were fine. I think I tracked the issue down to the room adjustment settings in BeatSaber.

### Steps for reproducing this issue:
- In BeatSaber, go to Settings -> Room Adjust and use the "Rotation" option to rotate the room by 180°
- Start a new song (only tested solo standard mode)
- Avatar should appear in front of you (if first person avatar is enabled, third person camera should show an avatar looking "backwards" while the HMD is looking "forward" on the stage)

Tracking is fine, the avatar location in the room is just wrong by 180° in this example. But all movement of head and hands are correct. I've changed to 90° and 270° orientation for testing purposes and the avatar spawned sideways. So I'm guessing the issue is with changes in the room orientation. When resetting the room adjustments, everything works as expected.

Note: Avatar location in main menu is correct all the time. Also, when opening the menu during a song, the avatar snaps back into the correct position and it stays there for the duration of the song after clicking "Continue". Clicking "Restart" will put it back into the wrong location.

Affected version: v.3.1.1-beta

Btw: Thank you very much for your work on these plugins :)

**Comment by xyonico** [comment]
I've looked into this and found the issue. This has been fixed in [v3.1.2-beta](https://github.com/xyonico/CustomAvatarsPlugin/releases/tag/v3.1.2-beta).

Thanks for the breakdown of the bug, it helped to fix it.
